"""Document service for generating Word documents (.docx), PDF, and TXT"""
# pyright: reportAttributeAccessIssue=false, reportArgumentType=false, reportOperatorIssue=false, reportCallIssue=false, reportGeneralTypeIssues=false
from __future__ import annotations
import re
from typing import TYPE_CHECKING

from docx import Document as DocxDocument
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from fpdf import FPDF
from pathlib import Path
from sqlalchemy.orm import Session
from datetime import datetime

from app.core.config import settings
from app.models import Book, Outline, Chapter
from app.services.context_service import context_service

if TYPE_CHECKING:
    from docx.document import Document as DocumentType


class DocumentService:
    """Service for compiling book chapters into Word documents, PDF, and TXT"""

    @staticmethod
    def _clean_markdown(text: str) -> str:
        """Remove markdown formatting from text"""
        # Remove headings (## , ### , etc.)
        text = re.sub(r'^#{1,6}\s+', '', text, flags=re.MULTILINE)
        # Remove bold **text** or __text__
        text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
        text = re.sub(r'__(.+?)__', r'\1', text)
        # Remove italic *text* or _text_ (single)
        text = re.sub(r'(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)', r'\1', text)
        text = re.sub(r'(?<!_)_(?!_)(.+?)(?<!_)_(?!_)', r'\1', text)
        # Remove inline code `text`
        text = re.sub(r'`(.+?)`', r'\1', text)
        # Remove horizontal rules (---, ***)
        text = re.sub(r'^[-*_]{3,}\s*$', '', text, flags=re.MULTILINE)
        # Remove blockquote markers
        text = re.sub(r'^>\s?', '', text, flags=re.MULTILINE)
        # Clean up extra blank lines
        text = re.sub(r'\n{3,}', '\n\n', text)
        return text.strip()

    def compile_book_to_docx(
        self,
        db: Session,
        book_id: int
    ) -> str:
        """
        Compile all chapters of a book into a .docx file.
        
        Args:
            db: Database session
            book_id: Book ID
        
        Returns:
            Path to the generated .docx file
        
        Raises:
            ValueError: If book or chapters not found
        """
        # Get book data
        book = db.query(Book).filter(Book.id == book_id).first()
        if not book:
            raise ValueError(f"Book with ID {book_id} not found")
        
        outline = db.query(Outline).filter(Outline.book_id == book_id).first()
        chapters = context_service.get_all_chapters_for_compilation(db, book_id)
        
        if not chapters:
            raise ValueError(f"No chapters found for book ID {book_id}")
        
        # Create document
        doc = DocxDocument()
        
        # Add title page
        self._add_title_page(doc, book.title)
        
        # Add page break
        doc.add_page_break()
        
        # Add table of contents placeholder
        self._add_table_of_contents(doc, chapters)
        doc.add_page_break()
        
        # Add outline if exists
        if outline and outline.outline_content:  # type: ignore
            self._add_outline_section(doc, outline.outline_content)
            doc.add_page_break()
        
        # Add chapters
        for chapter in chapters:
            self._add_chapter(doc, chapter)
            doc.add_page_break()
        
        # Save document
        output_dir = Path(settings.output_dir)
        output_dir.mkdir(exist_ok=True)
        
        # Create filename
        safe_title = "".join(c for c in book.title if c.isalnum() or c in (' ', '-', '_')).strip()
        safe_title = safe_title.replace(' ', '_')
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{safe_title}_{book_id}_{timestamp}.docx"
        file_path = output_dir / filename
        
        # Save
        doc.save(str(file_path))
        
        return str(file_path)
    
    def _add_title_page(self, doc: DocxDocument, title: str):
        """Add a title page to the document"""
        # Title
        title_para = doc.add_paragraph()
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title_para.add_run(title)
        title_run.font.size = Pt(28)
        title_run.font.bold = True
        
        # Add some space
        doc.add_paragraph()
        doc.add_paragraph()
        
        # Generated by info
        info_para = doc.add_paragraph()
        info_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        info_run = info_para.add_run(f"Generated by {settings.app_name}")
        info_run.font.size = Pt(12)
        info_run.font.italic = True
        
        date_para = doc.add_paragraph()
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date_run = date_para.add_run(datetime.now().strftime("%B %d, %Y"))
        date_run.font.size = Pt(12)
    
    def _add_table_of_contents(self, doc: DocxDocument, chapters):
        """Add a table of contents"""
        heading = doc.add_heading('Table of Contents', level=1)
        
        for chapter in chapters:
            toc_para = doc.add_paragraph(style='List Number')
            toc_para.add_run(f"{chapter.title if chapter.title else f'Chapter {chapter.chapter_number}'}")
    
    def _add_outline_section(self, doc: DocxDocument, outline_content: str):
        """Add the book outline section"""
        doc.add_heading('Book Outline', level=1)
        
        cleaned = self._clean_markdown(outline_content)
        paragraphs = cleaned.split('\n')
        for para in paragraphs:
            if para.strip():
                p = doc.add_paragraph(para.strip())
                p.style = 'Normal'
    
    def _add_chapter(self, doc: DocxDocument, chapter: Chapter):
        """Add a chapter to the document"""
        # Chapter heading
        chapter_title = chapter.title if chapter.title else f"Chapter {chapter.chapter_number}"  # type: ignore
        doc.add_heading(f"Chapter {chapter.chapter_number}: {chapter_title}", level=1)
        
        # Chapter content
        if chapter.content:  # type: ignore
            cleaned = self._clean_markdown(chapter.content)
            paragraphs = cleaned.split('\n')
            for para in paragraphs:
                if para.strip():
                    p = doc.add_paragraph(para.strip())
                    p.style = 'Normal'
                    # Add spacing between paragraphs
                    p.paragraph_format.space_after = Pt(12)


    def compile_book_to_pdf(self, db: Session, book_id: int) -> str:
        """Compile all chapters into a PDF file"""
        book = db.query(Book).filter(Book.id == book_id).first()
        if not book:
            raise ValueError(f"Book with ID {book_id} not found")

        chapters = context_service.get_all_chapters_for_compilation(db, book_id)
        if not chapters:
            raise ValueError(f"No chapters found for book ID {book_id}")

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Title page
        pdf.add_page()
        pdf.set_font('Helvetica', 'B', 28)
        pdf.ln(60)
        pdf.cell(0, 20, book.title, ln=True, align='C')
        pdf.set_font('Helvetica', 'I', 12)
        pdf.ln(10)
        pdf.cell(0, 10, f"Generated by {settings.app_name}", ln=True, align='C')
        pdf.cell(0, 10, datetime.now().strftime("%B %d, %Y"), ln=True, align='C')

        # Chapters
        for chapter in chapters:
            pdf.add_page()
            chapter_title = chapter.title if chapter.title else f"Chapter {chapter.chapter_number}"
            pdf.set_font('Helvetica', 'B', 18)
            pdf.cell(0, 12, f"Chapter {chapter.chapter_number}: {chapter_title}", ln=True)
            pdf.ln(5)

            if chapter.content:
                cleaned = self._clean_markdown(chapter.content)
                pdf.set_font('Helvetica', '', 11)
                for para in cleaned.split('\n'):
                    if para.strip():
                        pdf.multi_cell(0, 6, para.strip())
                        pdf.ln(3)

        # Save
        output_dir = Path(settings.output_dir)
        output_dir.mkdir(exist_ok=True)
        safe_title = "".join(c for c in book.title if c.isalnum() or c in (' ', '-', '_')).strip().replace(' ', '_')
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{safe_title}_{book_id}_{timestamp}.pdf"
        file_path = output_dir / filename
        pdf.output(str(file_path))
        return str(file_path)

    def compile_book_to_txt(self, db: Session, book_id: int) -> str:
        """Compile all chapters into a plain text file"""
        book = db.query(Book).filter(Book.id == book_id).first()
        if not book:
            raise ValueError(f"Book with ID {book_id} not found")

        chapters = context_service.get_all_chapters_for_compilation(db, book_id)
        if not chapters:
            raise ValueError(f"No chapters found for book ID {book_id}")

        lines = []
        lines.append(book.title.upper())
        lines.append('=' * len(book.title))
        lines.append(f"Generated by {settings.app_name}")
        lines.append(datetime.now().strftime("%B %d, %Y"))
        lines.append('')
        lines.append('')

        for chapter in chapters:
            chapter_title = chapter.title if chapter.title else f"Chapter {chapter.chapter_number}"
            lines.append(f"Chapter {chapter.chapter_number}: {chapter_title}")
            lines.append('-' * 40)
            if chapter.content:
                cleaned = self._clean_markdown(chapter.content)
                lines.append(cleaned)
            lines.append('')
            lines.append('')

        # Save
        output_dir = Path(settings.output_dir)
        output_dir.mkdir(exist_ok=True)
        safe_title = "".join(c for c in book.title if c.isalnum() or c in (' ', '-', '_')).strip().replace(' ', '_')
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{safe_title}_{book_id}_{timestamp}.txt"
        file_path = output_dir / filename
        file_path.write_text('\n'.join(lines), encoding='utf-8')
        return str(file_path)


# Global service instance
document_service = DocumentService()
